const stories = [
  {
    text: "Senhor, relatório de situação. As nossas unidades confirmam que o inimigo está a preparar %!1 coordenado com %!2 infiltradas %!3. Detetámos movimentação de %!4 a convergir para %!5 com previsão de chegada %!6. Intercetámos comunicações que indicam o uso de %!7 com o código %!8. Os nossos radares identificaram %!9 a aproximarem-se %!10, possivelmente para um ataque aéreo de diversão. A inteligência apurou que o objetivo principal é capturar %!11 e desativar %!12. Solicito autorização para ativar o plano de contingência e mobilizar as reservas.",
    count: 12,
    prompts: [
      [
        "UM ATAQUE CIBERNETICO",
        "UMA OFENSIVA BIOLOGICA",
        "UMA CAMPANHA DE DESINFORMACAO",
      ],
      [
        "UNIDADES DE INFANTARIA",
        "FORCAS ESPECIAIS",
        "MERCENARIOS ESTRANGEIROS",
      ],
      ["NA ZONA INDUSTRIAL", "NO COMPLEXO GOVERNAMENTAL", "NA BASE AEREA"],
      ["TANQUES PESADOS", "VEICULOS ANFIBIOS", "DRONES DE ATAQUE"],
      ["A PONTE PRINCIPAL", "O AEROPORTO INTERNACIONAL", "A CENTRAL ELETRICA"],
      ["AS 06H00", "AO AMANHECER", "EM 4 HORAS"],
      ["MUNICOES EXPERIMENTAIS", "ARMAS QUIMICAS", "PULSOS ELETROMAGNETICOS"],
      ["FENIX", "HYDRA", "TEMPESTADE"],
      ["AVIOES DE COMBATE", "HELICOPTEROS DE ATAQUE", "BOMBARDEIROS FURTIVOS"],
      [
        "PELO QUADRANTE LESTE",
        "PELO CORREDOR NORTE",
        "PELO ESPACO AEREO RESTRITO",
      ],
      [
        "O CENTRO DE COMUNICACOES",
        "O DEPOSITO DE ARMAS",
        "O LIDER DA RESISTENCIA",
      ],
      [
        "OS NOSSOS SISTEMAS DE DEFESA",
        "A REDE DE ENERGIA",
        "O SISTEMA DE VIGILANCIA",
      ],
    ],
  },
  {
    count: 12,
    text: "Relatório urgente. O módulo %!1 da estação sofreu uma falha crítica. Os sistemas %!2 estão a falhar e a resposta da equipa de engenharia %!3 está atrasada. Detectámos sinais de %!4 que comprometem a integridade do casco no sector %!5. Os níveis de oxigénio caíram para %!6, colocando a tripulação em risco. Tentámos activar o protocolo de emergência %!7, mas há uma avaria no gerador %!8. Contactámos a nave %!9, a caminho da estação, para assistência, previsão de chegada %!10. Abaixo da ponte principal, o %!11 registou actividade incomum, possivelmente %!12. A situação exige evacuação se não houver estabilização imediata.",
    prompts: [
      ["DE COMUNICACOES", "DE PROPULSAO", "DE SUPORTE VITAL"],
      ["ELETRICOS", "HIDRAULICOS", "DE CONTROLO AMBIENTAL"],
      ["NO SECTOR NORTE", "NO HANGAR PRINCIPAL", "JUNTO AO LABORATORIO"],
      ["RADIACOES ANOMALAS", "FLUTUACOES MAGNETICAS", "MICRO METEORITOS"],
      ["7B", "3D", "ZONA DE CARGA"],
      ["65%", "40%", "25%"],
      ["DE ISOLAMENTO", "DE DESCIDA RAPIDA", "DE CONTENCAO"],
      ["PRINCIPAL", "AUXILIAR", "DE EMERGENCIA"],
      ["ENDEAVOUR VII", "PIONEER X", "HORIZON ALPHA"],
      ["EM 30 MINUTOS", "EM 1 HORA", "EM 2 HORAS"],
      ["SENSOR DE MOVIMENTO", "DETETOR TERMICO", "CAMARA DE VIGILANCIA"],
      [
        "UMA INTRUSAO NAO AUTORIZADA",
        "UM PICO DE ENERGIA",
        "UMA FALHA NO SISTEMA",
      ],
    ],
  },
  {
    count: 12,
    text: "Encontrei algo estranho na mansão. A porta do %!1 estava trancada por dentro. Aparentemente, a vítima estava a investigar %!2 antes de morrer. A polícia encontrou %!3 escondido no quarto. Os registos mostram que a família tinha dívidas com %!4. O mordomo afirma ter visto %!5 perto da biblioteca. A chave do cofre estava %!6. A vítima tinha um encontro secreto com %!7. A última mensagem no telemóvel da vítima era sobre %!8. Os cães ladraram incessantemente para %!9. A análise forense revelou vestígios de %!10 na chávena da vítima. O detetive suspeita de %!11 devido ao seu passado com %!12. Precisamos de mais informações.",
    prompts: [
      ["ESCRITORIO", "CAVE", "QUARTO DOS HOSPEDES"],
      ["UM ANTIGO ARTEFACTO", "UM CASO DE CORRUPCAO", "SEGREDOS DE FAMILIA"],
      ["UMA ARMA", "UM DIARIO", "UMA FOTOGRAFIA"],
      ["UM AGIOTA", "UM BANCO SUICO", "A MAFIA LOCAL"],
      ["UMA FIGURA SOMBRIA", "UM CARRO DESCONHECIDO", "O JARDINEIRO"],
      ["ESCONDIDA NUM LIVRO", "NO BOLSO DA VITIMA", "DESAPARECIDA"],
      ["A AMANTE", "O ADVOGADO", "UM ANTIGO SOCIO"],
      ["UMA HERANCA", "UM NEGOCIO ARRISCADO", "UMA AMEACA"],
      ["O PORTAO", "A FLORESTA", "O POCO"],
      ["VENENO", "SEDATIVOS", "UMA SUBSTANCIA DESCONHECIDA"],
      ["O FILHO", "A ESPOSA", "O VIZINHO"],
      ["JOGOS DE AZAR", "UM ESCANDALO", "A VITIMA"],
    ],
  },
  {
    count: 12,
    text: "Capitão, recebemos um sinal de socorro da nave %!1. Eles foram atacados por piratas espaciais perto do planeta %!2. Os piratas roubaram %!3 e fugiram para %!4. A nave está danificada e precisa de %!5. A tripulação relata que os piratas usavam armas %!6. O líder dos piratas é conhecido como %!7. Eles têm uma base secreta em %!8. A nossa missão é recuperar %!9 e capturar os piratas. A nave pirata é uma %!10. Eles estão a planear atacar %!11 para roubar %!12. Preparem-se para o combate!",
    prompts: [
      ["ESTRELA ERRANTE", "AURORA BOREAL", "ANDROMEDA V"],
      ["XYLOS", "KRYPTON 7", "VEGA PRIME"],
      ["CRISTAIS DE ENERGIA", "TECNOLOGIA EXPERIMENTAL", "OURO INTERESTELAR"],
      ["O SISTEMA NEBULA", "A ZONA DE ASTEROIDES", "O BURACO NEGRO"],
      ["REPAROS URGENTES", "SUPORTE MEDICO", "COMBUSTIVEL"],
      ["DE PLASMA", "SONICAS", "DE RADIACAO"],
      ["BARBA NEGRA", "OLHO DE FOGO", "DENTE DE SABRE"],
      [
        "UMA LUA DESERTA",
        "UM ASTEROIDE CAMUFLADO",
        "UMA ESTACAO ESPACIAL ABANDONADA",
      ],
      ["A CARGA ROUBADA", "OS REFENS", "A TECNOLOGIA SECRETA"],
      ["CORSARIO", "PREDADOR", "VINGADOR"],
      [
        "A COLONIA DE NOVA ESPERANCA",
        "O POSTO DE COMERCIO ESPACIAL",
        "A BASE MILITAR",
      ],
      ["SUPRIMENTOS MEDICOS", "COMPONENTES DE NAVE", "DADOS DE INTELIGENCIA"],
    ],
  },
  {
    count: 12,
    text: "Temos um problema. O agente %!1 foi comprometido. Ele estava a transmitir informações sobre %!2. A fonte dele era %!3. Os russos estão a planear %!4. Precisamos de o extrair antes que %!5. A localização segura é %!6. Ele tem informações sobre %!7. A palavra-chave para o contacto é %!8. A equipa de resgate está a usar %!9. Os russos estão a usar %!10 para o rastrear. A nossa prioridade é proteger %!11 e evitar %!12. A situação é crítica.",
    prompts: [
      ["AGUIA", "CORVO", "LINCE"],
      ["O PROGRAMA NUCLEAR", "A LOCALIZACAO DAS BASES", "A NOVA ARMA"],
      ["UM OFICIAL DO KGB", "UMA CIENTISTA", "UM DIPLOMATA"],
      [
        "UM ATAQUE SURPRESA",
        "UMA OPERACAO DE SABOTAGEM",
        "UMA CAMPANHA DE DESINFORMACAO",
      ],
      ["O CAPTUREM", "O MATEM", "REVELE OS SEGREDOS"],
      ["A EMBAIXADA", "UM ESCONDERIJO", "UM PONTO DE ENCONTRO"],
      [
        "A IDENTIDADE DOS ESPIOES",
        "OS PLANOS DE INVASAO",
        "A TECNOLOGIA ROUBADA",
      ],
      ["AURORA", "TEMPESTADE", "ECLIPSE"],
      ["UM DISFARCE", "UM TUNEL SECRETO", "UM HELICOPTERO"],
      ["ESCUTAS TELEFONICAS", "AGENTES DUPLOS", "TECNOLOGIA DE RASTREAMENTO"],
      ["A SUA IDENTIDADE", "OS DOCUMENTOS", "A SUA VIDA"],
      ["UMA GUERRA", "UM ESCANDALO INTERNACIONAL", "A SUA CAPTURA"],
    ],
  },
  {
    text: "Recebemos um relatório sobre acontecimentos estranhos na rua %!1. As vítimas relataram %!2 durante a noite. Foram encontrados vestígios de %!3 perto do local. A testemunha viu uma figura %!4 entrar na casa. A polícia está a procurar %!5 suspeitos. Houve um roubo de %!6 no mercado local. O modus operandi sugere %!7. As câmaras de segurança mostraram %!8 passando na rua. Encontrámos uma pista ligada a %!9. O inspetor acredita que %!10 está envolvido. A operação vai buscar %!11 para interrogatório. Precisamos evitar %!12 para não alarmar a população.",
    count: 12,
    prompts: [
      ["DAS ACACIAS", "DA LIBERDADE", "DO PINHAL"],
      [
        "RUIDOS INEXPLICAVEIS",
        "DESAPARECIMENTOS SUBITOS",
        "APAGOES FREQUENTES",
      ],
      ["PEGADAS ESTRANHAS", "VESTIGIOS DE POLVORA", "FIBRAS TEXTEIS"],
      ["ENCAPUCADA", "ALTA E MAGRA", "COM BONE"],
      ["DOIS", "UMA MULHER", "UM GRUPO"],
      ["JOIAS", "DINHEIRO", "ELETRONICOS"],
      ["CRIME ORGANIZADO", "UM CRIME POR VINGANCA", "UM AMADOR APRESSADO"],
      ["UM CARRO PRETO", "UMA MOTA", "UMA CARRINHA BRANCA"],
      ["UMA SEITA LOCAL", "UM GANGUE RIVAL", "UM TRAFICANTE"],
      ["O FILHO", "A ESPOSA", "O VIZINHO"],
      ["UM SUSPEITO PRINCIPAL", "UM INFORMADOR CHAVE", "UM CUMPLICE"],
      ["PANICO DESNECESSARIO", "FUGA DOS SUSPEITOS", "UMA IMPRENSA VORAZ"],
    ],
  },
  {
    text: "O grupo da expedição chegou ao %!1. Encontrámos sinais de %!2 espalhados pela região. Um dos membros relatou ter ouvido %!3 durante a noite. Estamos a monitorizar %!4 que se desloca nas proximidades. Descobrimos ruínas antigas de %!5 escondidas atrás das árvores. A provisão de água será suficiente para %!6 dias. A comunicação foi interrompida devido a %!7. Avistámos uma tribo local conhecida como %!8. Precauções contra %!9 foram reforçadas. O líder da equipa sugeriu investigar %!10 para encontrar respostas. As condições meteorológicas apontam para %!11. O objetivo principal é encontrar %!12 e voltar em segurança.",
    count: 12,
    prompts: [
      ["RIO ESCONDIDO", "VALE DAS SOMBRAS", "CACHOEIRA DO CEU"],
      [
        "PEGADAS GIGANTES",
        "MARCAS DE QUEIMADAS",
        "INDICADORES DE ANIMAIS SELVAGENS",
      ],
      ["GRITOS ESTRANHOS", "CANTOS DE PASSAROS EXOTICOS", "SONS DE BATIDAS"],
      ["PREDADORES", "ANIMAIS NOTURNOS", "TRIBOS DESCONHECIDAS"],
      ["CERIMONIAS ANTIGAS", "TEMPLOS ESQUECIDOS", "ARTEFACTOS MISTERIOSOS"],
      ["7", "10", "14"],
      [
        "FALHAS NAS ANTENAS",
        "TEMPESTADES ELETRICAS",
        "INTERFERENCIAS NATURAIS",
      ],
      ["OS TUPINIKIM", "OS JE", "OS XAVANTES"],
      ["PICADAS DE INSETOS", "DOENCAS TROPICAIS", "ATAQUES DE COBRAS"],
      ["O LAGO SAGRADO", "A CAVERNA MISTERIOSA", "A MONTANHA SAGRADA"],
      ["CHUVAS INTENSAS", "CALOR EXTREMO", "VENTOS FORTES"],
      ["A PLANTA CURATIVA", "O ANIMAL LENDARIO", "O MAPA ANTIGO"],
    ],
  },
  {
    text: "A equipa de resgate recebeu uma chamada do %!1. A zona foi afetada por %!2 há %!3 horas. As comunicações estão a ser dificultadas por %!4. Estão a ser reportadas pessoas presas em %!5. As forças de segurança indicaram que %!6 está bloqueado devido a %!7. Contamos com %!8 para apoio durante a operação. As condições climáticas incluem %!9. Detectámos um risco potencial de %!10 na área. O comandante quer garantir %!11 para minimizar perdas. A prioridade número um é o resgate de %!12.",
    count: 12,
    prompts: [
      ["HOSPITAL CENTRAL", "BAIRRO AS FLORES", "ZONA INDUSTRIAL"],
      ["UM TERRAMOTO", "UMA INUNDAO", "UM INCENDIO FLORESTAL"],
      ["2", "5", "8"],
      ["QUEDA DE SINAIS", "TEMPESTADES ELETRICAS", "BLOQUEIOS DE SINAL"],
      ["UM PREDIO EM COLAPSO", "UM TUNEL SUBTERRANEO", "UMA PONTE DANIFICADA"],
      ["A ESTRADA PRINCIPAL", "A VIA FERREA", "O ACESSO AO AEROPORTO"],
      [
        "QUEDA DE ARVORES",
        "DESLIZAMENTO DE TERRAS",
        "BLOQUEIOS CAUSADOS POR DESTROCOS",
      ],
      [
        "A BRIGADA DE BOMBEIROS",
        "A POLICIA MILITAR",
        "A UNIDADE MEDICA DE EMERGENCIA",
      ],
      ["CHUVAS FORTES", "NEVOEIRO DENSO", "VENTOS FORTES"],
      ["NOVO DESLIZAMENTO", "INUNDACOES SECUNDARIAS", "INCENDIOS ESPALHADOS"],
      ["A EVACUACAO RAPIDA", "A COORDENACAO PERFEITA", "O APOIO LOGISTICO"],
      ["SOBREVIVENTES", "EQUIPA DE EMERGENCIA", "EQUIPAMENTOS E PROVISOES"],
    ],
  },
  {
    text: "O piloto %!1 está a liderar na pista %!2 com uma velocidade de %!3 km/h. A equipa de mecânicos reportou %!4 na nave que precisa de ser corrigido. O adversário %!5 está a aproximar-se a %!6 segundos de distância. O público espera uma curva em %!7 metros que pode decidir a corrida. As condições da pista são %!8. O sistema de navegação tem uma falha em %!9. A próxima volta será decisiva para %!10. Verificámos %!11 a bordo após o último pit stop. O treinador instruiu %!12 para manter o ritmo e evitar riscos desnecessários.",
    count: 12,
    prompts: [
      ["NOVA FALCAO", "REX TURBO", "VIPER X"],
      ["NEON SPEEDWAY", "CIRCUITO ALPHA", "ESTRADA QUANTUM"],
      ["320", "298", "305"],
      [
        "UM PROBLEMA NO MOTOR",
        "FALTA DE COMBUSTIVEL",
        "UM SISTEMA DE ARREFECIMENTO AVARIADO",
      ],
      ["DRAGSTER Z", "FLASH PRIME", "TEMPESTADE"],
      ["2.4", "1.8", "3.1"],
      ["SECAS E LISAS", "MOLHADAS", "POUCO ADERENTES"],
      [
        "SENSORES FRONTAIS",
        "CONTROLO DE ESTABILIDADE",
        "SISTEMA DE COMUNICACAO",
      ],
      ["GARANTIR A VITORIA", "MANTER O SEGUNDO LUGAR", "ULTRAPASSAR O LIDER"],
      ["PEQUENAS AVARIAS", "AJUSTES NAS RODAS", "REFORCO DA SUSPENSAO"],
      ["NOVA FALCAO", "REX TURBO", "VIPER X"],
      ["NOVA FALCAO", "REX TURBO", "VIPER X"],
    ],
  },
  {
    text: "A equipa descobriu um sítio arqueológico em %!1. Foram encontrados fragmentos de %!2. Os escavadores reportaram %!3 durante a última campanha. Foi identificada uma inscrição que fala de %!4. O artefacto principal parece estar feito de %!5. Os perigos previstos incluem %!6. O clima registado aponta para %!7 nas próximas semanas. Utilizámos %!8 para mapear a região. O chefe da equipa recomendou cuidado com %!9. O próximo passo será analisar %!10 para entender o contexto. A expedição espera encontrar %!11. O relatório deverá ser enviado a %!12 para avaliação final.",
    count: 12,
    prompts: [
      ["O DESERTO DO SAHARA", "A PLANICIE DE GOBI", "O DESERTO DE ATACAMA"],
      ["CERAMICA ANTIGA", "OSSOS HUMANOS", "FERRAMENTAS DE PEDRA"],
      [
        "ESCORREGOES FREQUENTES",
        "TEMPESTADES DE AREIA",
        "INTERRUPCOES NAS ESCAVACOES",
      ],
      ["UM RITUAL PERDIDO", "CIVILIZACOES ESQUECIDAS", "CONFLITOS ANTIGOS"],
      ["OURO PURO", "BRONZE", "PEDRA CALCARIA"],
      [
        "SERPENTES VENENOSAS",
        "TERRITORIOS DE ANIMAIS SELVAGENS",
        "CONDICOES METEOROLOGICAS SEVERAS",
      ],
      ["CALOR EXTREMO", "SECAS PROLONGADAS", "TEMPESTADES DE AREIA"],
      ["DRONES DE MAPEAMENTO", "TECNOLOGIA LIDAR", "SENSORES GEOFISICOS"],
      ["COLAPSOS DE CAVERNAS", "ILHAS DE CALOR", "TERRITORIOS HOSTIS"],
      [
        "OS HIEROGLIFOS",
        "A LOCALIZACAO DA CIDADE PERDIDA",
        "OS PADROES DE ENTERRAMENTO",
      ],
      ["ARTEFACTOS SAGRADOS", "TESOUROS ESCONDIDOS", "RESIDUOS CULTURAIS"],
      [
        "O MUSEU NACIONAL",
        "A UNIVERSIDADE LOCAL",
        "A ORGANIZACAO ARQUEOLOGICA INTERNACIONAL",
      ],
    ],
  },

  {
    text: "Durante o festival anual em %!1, um incidente misterioso ocorreu na praça central. Testemunhas afirmam ter visto %!2 desaparecer repentinamente. Investigações iniciais revelaram sinais de %!3 próximos ao palco. As forças de segurança procuram %!4, que foram vistos pela última vez perto do %!5. A organização do evento cancelou %!6 após o ocorrido. O suspeito principal pode estar relacionado com %!7, um grupo conhecido por %!8. Câmeras de vigilância captaram %!9 movimentando-se estranhamente. A prefeitura avisou sobre %!10 para evitar pânico. Especialistas recomendam monitoramento rigoroso do %!11 e investigação aprofundada dos %!12 presentes.",
    count: 12,
    prompts: [
      ["SAO JOAO", "O CASTELO VELHO", "A PRACA DAS FLORES"],
      ["UMA PESSOA", "UMA SOMBRA", "UM OBJETO BRILHANTE"],
      ["PO QUIMICO", "MARCACOES ESTRANHAS", "FIMES DE LUZ"],
      ["TRES INDIVIDUOS", "UM HOMEM ALTO", "UMA MULHER DE CAPUZ"],
      ["BAR DO MIGUEL", "TEATRO MUNICIPAL", "MERCEARIA CENTRAL"],
      [
        "TODOS OS EVENTOS NOTURNOS",
        "A APRESENTACAO PRINCIPAL",
        "AS FEIRAS DE ARTESANATO",
      ],
      ["O GRUPO SOMBRIO", "A ORGANIZACAO LOCAL", "O CLA DOS REIS"],
      ["INVASOES", "PROTESTOS", "MAINHADAS"],
      ["UMA VELOCIDADE ESTRANHA", "UM OBJETO VOADOR", "UMA LUZ AZUL"],
      ["FALSOS BOATOS", "NOTICIAS FALSAS", "PANDEMONIO"],
      ["ACESSO AO PERIMETRO", "OS PUBLICOS", "OS SEGURANCAS"],
      ["DISPOSITIVOS ELETRONICOS", "EVIDENCIAS", "MENSAGENS SUSPEITAS"],
    ],
  },
  {
    text: "O arqueólogo %!1 descobriu uma tumba proibida na região de %!2. Símbolos enigmáticos indicam uma maldição ligada a %!3. A equipe relata fenômenos estranhos como %!4 dentro da tumba. Para proteger a tumba, construíram proteção com %!5. O mapa antigo sugere que artefatos como %!6 foram enterrados no local. A expedição enfrentou dificuldades devido a %!7. Um diário antigo mencionava um segredo em %!8. O tempo estimado para completar a missão é %!9 dias. Riscos incluem %!10 e membros da equipe foram instruídos a evitar %!11. A expedição espera que a descoberta revele %!12.",
    count: 12,
    prompts: [
      ["DR ALMEIDA", "DRA PEREIRA", "PROF COSTA"],
      ["PANTANAL", "SERTAO", "CAATINGA"],
      ["UM REI ESQUECIDO", "UMA DEUSA ANTIGA", "UM DEMONIO"],
      ["VULTOS SOMBRIOS", "SUSSURROS", "LANCES DE LUZ"],
      ["PEDRAS MAGICAS", "GRIMORIOS", "SIMBOLOS ENGRAVADOS"],
      ["UM COLAR DE OURO", "UMA ESPADA FORMIDAVEL", "UMA PEDRA RARA"],
      ["TEMPORAIS", "ANIMAIS SELVAGENS", "INSETOS VENGATIVOS"],
      ["A CAMARA PRINCIPAL", "O POCO CENTRAL", "A SALA SECRETA"],
      ["15", "30", "45"],
      ["DESABAMENTOS", "ATAQUES DE COBRAS", "DOENCAS DESCONHECIDAS"],
      ["LUGARES ESCUROS", "AGUA ESTAGNADA", "CERTAS ARMADILHAS"],
      ["SEUS MISTERIOS", "SUAS RIQUEZAS", "SUAS CONEXOES COM OUTROS SITIOS"],
    ],
  },
  {
    text: "Na cidade futurista de %!1, um vírus cibernético chamado %!2 está infectando todo o sistema. Usuários reportam falhas no %!3 que controlam suas residências e veículos autônomos. A corporação %!4 iniciou operações de contenção, isolando os setores %!5 e %!6. A inteligência descobriu que o hack está ligado a %!7, que quer %!8. Pessoas foram aconselhadas a desligar seus %!9 e informar a %!10 em caso de atividade suspeita. A previsão é de que o sistema esteja restaurado em %!11 horas. O especialista %!12 lidera o combate ao vírus.",
    count: 12,
    prompts: [
      ["NEON CITY", "ULTRA METROPOLE", "CYBERHAVEN"],
      ["SHADOW SPIKE", "BLACK NET", "VOID CORRUPTION"],
      ["EFEITOS DOMESTICOS", "SISTEMAS DE SEGURANCA", "INTERFACES PESSOAIS"],
      ["TECHNOVEX", "CYBERCORP", "DATALINK"],
      ["CENTRO DE COMANDO", "SETOR INDUSTRIAL", "BAIRRO TECNOLOGICO"],
      ["DISTRITO FINANCEIRO", "ZONA RESIDENCIAL", "AREA DE TRANSPORTE"],
      ["HACKERS ANONIMOS", "GRUPO DARKWEB", "ORGANIZACAO REVOLUCIONARIA"],
      ["DOMINAR A CIDADE", "DESATIVAR OS SISTEMAS", "COLETAR INFORMACOES"],
      ["APARELHOS", "INTELIGENCIAS ARTIFICIAIS", "REDES PESSOAIS"],
      ["CENTRAL DE INCIDENTES", "AUTHORITY NET", "GUARDIOES DIGITAIS"],
      ["6", "12", "24"],
      ["DR KIM", "ENG SOLANO", "DR CARTER"],
    ],
  },
  {
    text: "Na competição de culinária em %!1, o chef %!2 apresentou um prato inovador feito com %!3. Durante a prova, um incidente com %!4 causou um atraso. Jurados ressaltaram a importância de %!5 para equilíbrio de sabor. O ingrediente secreto foi %!6, oriundo de %!7. A equipe técnica avaliou a textura como %!8 e a apresentação visual teve %!9. O desafio final será preparar um prato %!10 em %!11 minutos. A vitória pode garantir ao chef %!12 um contrato internacional.",
    count: 12,
    prompts: [
      ["GASTROFEST", "FESTIVAL SABORES", "CONCURSO DO CHEF"],
      ["CARLA MORAES", "LUIS SANTOS", "MARTA LOPES"],
      ["CAVIAR DE ALGAS", "PIMENTA ROSA", "TRUFAS NEGRA"],
      [
        "UM FOGO NA COZINHA",
        "UM ACIDENTE COM GERADOR",
        "FALTA DE INGREDIENTES",
      ],
      [
        "TEMPEROS BIOLOGICOS",
        "FRESCOR DOS INGREDIENTES",
        "EQUILIBRIO DOS SABORES",
      ],
      ["FRUTAS EXOTICAS", "ERVAS REGIONAIS", "MARISCO FRESCO"],
      ["BRASIL", "PORTUGAL", "TAILANDIA"],
      ["DELICADA", "ENCORPADAS", "SUAVES"],
      ["EXCELENTES COMENTARIOS", "CRITICAS MISTAS", "PONTUACAO ALTA"],
      ["VEGETARIANO", "MARITIMO", "FUSAO"],
      ["45", "60", "90"],
      [
        "UMA OPORTUNIDADE DE OURO",
        "PREMIO DE RECONHECIMENTO",
        "UMA VAGA NA SELECAO MUNDIAL",
      ],
    ],
  },
  {
    text: "Durante a missão de resgate em %!1, a equipe enfrentou desafios devido a %!2. O piloto %!3 conseguiu pousar o helicóptero em uma área %!4 enquanto a equipe de campo usava %!5 para localizar sobreviventes. Os principais obstáculos foram %!6 e %!7 que atrasaram a operação. A comunicação com o centro foi mantida por %!8. Foram localizadas pessoas presas em %!9 e todas receberam %!10 antes da evacuação. O comandante pediu reforços com %!11 para assegurar as operações. Espera-se que o tempo melhore nas próximas %!12 horas.",
    count: 12,
    prompts: [
      ["VALE SOMBRIO", "REGIAO ARTICA", "MONTANHAS ROCHOSAS"],
      ["TEMPESTADE DE NEVE", "DESLIZAMENTO DE TERRA", "INUNDACOES"],
      ["SARGENTO ALVES", "CAPITAO LIMA", "TENENTE FERREIRA"],
      ["COMPLICADA", "ESCARPADA", "LIMITADA"],
      ["DRONES DE BUSCA", "CAES DE RESGATE", "SENSORES TERMAIS"],
      [
        "CONDICOES CLIMATICAS ADVERSAS",
        "TERRENO ACIDENTADO",
        "FALTA DE VISIBILIDADE",
      ],
      ["PERIGOS DE DESABAMENTOS", "ANIMAIS SELVAGENS", "BARREIRAS NATURAIS"],
      ["RADIO DE ALTA FREQUENCIA", "REDE SATELITAL", "COMUNICADORES PORTATEIS"],
      ["UM EDIFICIO COLAPSADO", "UMA CAVERNA", "UM TUNEL"],
      ["PRIMEIROS SOCORROS", "SUPRIMENTOS MEDICOS", "VESTIMENTAS TERMICAS"],
      ["UNIDADES ADICIONAIS", "VEICULOS PESADOS", "EQUIPES DE SUPORTE"],
      ["12", "24", "36"],
    ],
  },
  {
    text: "O laboratório em %!1 iniciou testes com uma nova fonte de energia baseada em %!2. Os cientistas %!3 relatam que a substância %!4 pode alterar propriedades físicas de materiais como %!5. Durante o experimento, houve uma reação inesperada que gerou %!6 em uma área restrita. As medidas de segurança envolveram o uso de %!7 para contenção. A previsão é que os testes continuem por mais %!8 meses. Resultados preliminares indicam impacto potencial em %!9 e aplicações em %!10. A equipe avalia riscos relacionados à %!11 e integridade estrutural do laboratório. Autoridades locais estão sendo notificadas para %!12.",
    count: 12,
    prompts: [
      ["ALFA CENTAURI", "ESTACAO NEBULA", "OBSERVATORIO SOLAR"],
      ["FOTONS QUANTICOS", "MATERIA ESCURA", "PLASMA FRIO"],
      ["DA EQUIPE PRINCIPAL", "DE PESQUISA AVANCADA", "INTERDISCIPLINARES"],
      ["INSTAVEL", "REATIVA", "NUNCA ANTES VISTA"],
      ["METAL", "VIDRO", "PLASTICO"],
      ["UMA BOLHA DE ENERGIA", "CHAMAS AZUIS", "UM VAZAMENTO DE RADIACAO"],
      [
        "CAMARAS DE ULTRAVIOLETA",
        "BARREIRAS DE CONTENCAO",
        "SISTEMAS DE FILTRAGEM",
      ],
      ["6", "12", "18"],
      ["TECNOLOGIA ESPACIAL", "INDUSTRIA FARMACEUTICA", "AUTOMOTIVO"],
      ["ENERGIA RENOVAVEL", "COMPUTACAO QUANTICA", "NANOTECNOLOGIA"],
      ["CONTAMINACAO", "COLAPSO ESTRUTURAL", "EXPOSICAO HUMANA"],
      ["EMISSAO DE ALERTAS", "EVACUACAO", "MEDIDAS DE PREVENCAO"],
    ],
  },
  {
    text: "No campeonato mundial de robótica em %!1, a equipe %!2 apresentou um robô %!3 capaz de realizar tarefas %!4 com precisão. Durante as provas, o robô enfrentou problemas no %!5, causando atrasos. A competição incluiu desafios como %!6 e %!7. A equipe rival %!8 destacou-se com uma solução inovadora baseada em %!9. Os juízes valorizaram o desempenho na categoria %!10. O prêmio final pode ser ganho com %!11. O diretor da equipe, %!12, acredita no potencial do grupo para alcançar a vitória.",
    count: 12,
    prompts: [
      ["TOKYO", "ZURIQUE", "SAO FRANCISCO"],
      ["TECHNOBOTS", "MECHAWIZARDS", "CYBERFORCE"],
      ["AUTONOMO", "HUMANOIDE", "INDUSTRIAL"],
      ["COMPLEXAS", "REPETITIVAS", "PERIGOSAS"],
      ["SISTEMA DE NAVEGACAO", "MECANISMO DE PINCAO", "CONTROLADOR DE FORCA"],
      ["NAVEGACAO", "MANIPULACAO", "PROCESSAMENTO DE IMAGENS"],
      ["INTERACAO HUMANA", "RESISTENCIA", "EFICIENCIA ENERGETICA"],
      ["GECKO TECH", "ROBOCLAN", "IRONWORKS"],
      ["INTELIGENCIA ARTIFICIAL", "SENSORES AVANCADOS", "MATERIAIS LEVES"],
      ["MANIPULADORES", "EXPLORADORES", "SOLDADORES"],
      ["APRESENTACAO ENGENHOSA", "TEMPO DE REACAO", "ACURACIA"],
      ["ENG TANAKA", "DRA MORGAN", "PROF LIMA"],
    ],
  },
  {
    text: "O navio cargueiro %!1 relatou problemas durante a travessia do %!2. A tripulação identificou uma falha no %!3, causando instabilidade. O sistema %!4 está temporariamente offline, exigindo reparos urgentes. O capitão %!5 solicitou auxílio via rádio para a área %!6. Condições marítimas %!7 dificultam as operações. O equipamento de segurança inclui %!8 e %!9. Foi detectada presença de %!10 próxima ao navio, aumentando o risco. A previsão de chegada ao porto de %!11 foi postergada para %!12.",
    count: 12,
    prompts: [
      ["MARINER X", "ATLANTIS", "POSEIDON"],
      ["ATLANTICO NORTE", "PACIFICO SUL", "INDICO"],
      ["MOTOR PRINCIPAL", "SISTEMA HIDRAULICO", "NAVEGACAO ELETRONICA"],
      ["DE COMUNICACAO", "DE ESTABILIDADE", "DE PROPULSAO"],
      ["CAPITAO MORAES", "CAPITA SOUZA", "CAPITAO REIS"],
      ["DE RESGATE", "DE INTERCEPTACAO", "DE CONTROLE MARITIMO"],
      ["TURBULENTAS", "CALMAS", "TEMPESTUOSAS"],
      ["BOTES SALVA-VIDAS", "COLETES SALVA-VIDAS", "RADIOCOMUNICADORES"],
      ["SONARES", "RADARES", "SISTEMAS DE DETECCAO"],
      ["NAVIOS PIRATAS", "NAVIOS DESCONHECIDOS", "SUBMARINOS"],
      ["RIO DE JANEIRO", "SAO FRANCISCO", "NATAL"],
      ["72 HORAS", "5 DIAS", "1 SEMANA"],
    ],
  },
  {
    text: "Durante a expedição científica na floresta %!1, a equipe coletou amostras de %!2 consideradas raras. Foram documentados sons de %!3, sugerindo a presença de uma nova espécie. O equipamento %!4 apresentou falhas devido à umidade e %!5. Uma trilha misteriosa levou até %!6, onde descobriu-se artefatos %!7. Problemas climáticos, como %!8, impactaram o andamento da pesquisa. A equipe utilizou %!9 para se orientar e monitorar sinais vitais. O biólogo %!10 observou comportamento %!11 nos animais locais. A conclusão da pesquisa prevê a publicação em %!12.",
    count: 12,
    prompts: [
      ["AMAZONIA", "CONGOLES", "TAIGA SIBERIANA"],
      ["PLANTAS ENDEMICAS", "INSETOS", "MICRORGANISMOS"],
      [
        "CANTOS APARENTEMENTE HUMANOS",
        "RUIDOS INEXPLICAVEIS",
        "ECO DE ANIMAIS DESCONHECIDOS",
      ],
      ["ELETRONICO", "MECANICO", "OPTICO"],
      ["TEMPORAIS", "NEBLINA DENSAS", "VENTOS FORTES"],
      ["UM CAVERNO", "UMA AREA DE CARGA", "UM POCO"],
      ["PRIMITIVOS", "ANCESTRAIS", "MISTERIOSOS"],
      ["CHUVAS INTENSAS", "CALOR EXTREMO", "FRIO INTENSO"],
      ["GPS", "DRONES", "RADIOLOCALIZADORES"],
      ["DRA SILVA", "DR ALVES", "PROF MARTINS"],
      ["AGRESSIVO", "DEFENSIVO", "SOCIAL"],
      [
        "REVISTAS CIENTIFICAS",
        "JOURNAIS INTERNACIONAIS",
        "PUBLICACOES ACADEMICAS",
      ],
    ],
  },
  {
    text: "Durante o teste da nova arma %!1 no campo de provas de %!2, foi detectada uma instabilidade no sistema %!3. O engenheiro %!4 recomendou a suspensão do teste após observar %!5, que poderia causar %!6. A equipe de segurança ativou o protocolo %!7 para evacuação rápida. O efeito da instabilidade foi percebido em %!8 metros ao redor do ponto de teste. Dados preliminares indicam que o componente %!9 falhou devido a %!10. O monitoramento contínuo será feito pela %!11. O sucesso do teste determinará a liberação para uso em %!12.",
    count: 12,
    prompts: [
      ["LASER DE PULSO", "CANHAO DE PARTICULAS", "MISSIL IONICO"],
      ["ALFA", "BETA", "GAMA"],
      ["DE REFRIGERACAO", "DE DISPARO", "DE CONTROLE"],
      ["ENG SANTOS", "ENG LIMA", "ENG MENDES"],
      ["SOBREAQUECIMENTO", "VIBRACOES EXCESSIVAS", "DESCOMPENSACAO MAGNETICA"],
      ["DANOS CATASTROFICOS", "FALHAS NO HARDWARE", "RISCOS DE SEGURANCA"],
      ["VERDE", "AMARELO", "VERMELHO"],
      ["500", "1000", "1500"],
      ["MODULADOR", "CAPACITOR", "TRANSDUTOR"],
      ["SOBRECARGA ELETRICA", "FALHA MECANICA", "ERRO DE PROGRMACAO"],
      ["LABORATORIO CENTRAL", "CENTRO DE PESQUISA", "UNIDADE DE TESTES"],
      ["USO MILITAR", "CIVIL", "COMERCIAL"],
    ],
  },
  {
    text: "Em %!1, a equipe de vigilância identificou %!2 atividades suspeitas próximas a %!3. Informações indicam que o grupo %!4 planeja realizar %!5 durante a próxima Semana da Segurança. O líder conhecido como %!6 tenta recrutar membros oferecendo %!7. As câmeras captaram %!8 e mensagens criptografadas com a palavra %!9. Forças especiais foram acionadas para monitorar %!10 e neutralizar possíveis ameaças. A população foi alertada para %!11 e solicitada a informar qualquer acontecimento suspeito. As operações serão coordenadas a partir da base %!12.",
    count: 12,
    prompts: [
      ["METROPOLE NOVA", "CIDADE ALTA", "PARQUE INDUSTRIAL"],
      ["DIVERSAS", "INCOMUNS", "MISTERIOSAS"],
      ["O ARMAZEM 7", "A ESTACAO CENTRAL", "O COMPLEXO TECNOLOGICO"],
      ["OS LOBOS NEGROS", "A ORDEM SECRETA", "OS VIGILANTES"],
      ["ATAQUES CIBERNETICOS", "SABOTAGENS", "INVASOES"],
      ["CORVO", "FALCAO", "SATIRO"],
      ["DINHEIRO FACIL", "PROTECAO", "PODER"],
      ["INTRUSOS", "VEICULOS SUSPEITOS", "INDIVIDUOS ARMADOS"],
      ["RUBI", "FENIX", "ORION"],
      ["ZONAS RESTRITAS", "AREAS DE ALTA SEGURANCA", "PONTOS DE CONTROLE"],
      ["CUIDADO", "VIGILANCIA EXTRA", "DENUNCIAS"],
      ["BUNKER ARTICO", "BASE ALFA", "CENTRO OPERACIONAL"],
    ],
  },

  {
    text: "No parque nacional de %!1, foram avistados animais migrando devido a mudanças repentinas de %!2. Biólogos monitoram o comportamento de %!3, uma espécie ameaçada de extinção. As equipes usam %!4 para traquear os movimentos e coletar dados. O fenômeno climatérico é atribuído a %!5 ocorrendo nas últimas semanas. O centro de pesquisa em %!6 tem coordenado ações de preservação, incluindo a proteção de %!7. Grupos ambientais alertaram para o risco de %!8. A população local tem reportado %!9 e algumas áreas foram interditadas. O governo decretou um plano emergencial para %!10 e investiu recursos em %!11. O relatório final será entregue à Organização Mundial de %!12.",
    count: 12,
    prompts: [
      ["COSTA DO ATLANTICO", "AMAZONIA", "SAVANNA DA AFRICA"],
      ["TEMPERATURA", "PATRONES DE CHUVA", "VENTOS FORTES"],
      ["ELEFANTES", "TIGRES", "MENTES"],
      ["DRONES", "TELEMETROS", "SENSORES REMOTOS"],
      [
        "AQUECIMENTO GLOBAL",
        "DESTRUICAO DE HABITAT",
        "EFEITO DE ILHA DE CALOR",
      ],
      ["RIO DE JANEIRO", "BRASILIA", "SAO PAULO"],
      ["AREAS DE DESOVA", "NOSSOZEIROS", "MATA ATLANTICA"],
      ["INCENDIOS FLORESTAIS", "CACA ILEGAL", "EXPANSAO URBANA"],
      ["AVISTAMENTOS DE ANIMAIS", "ATIVIDADE DE MADEIREIROS", "ENCHENTES"],
      [
        "CONTROLE DE INCENDIOS",
        "REINTRODUCAO DE ESPECIES",
        "EDUCACAO AMBIENTAL",
      ],
      [
        "MONITORAMENTO SATELITAL",
        "RECURSOS PARA RAROS",
        "CAPACITACAO DE EQUIPES",
      ],
      ["NATUREZA", "MEIO AMBIENTE", "BIODIVERSIDADE"],
    ],
  },
  {
    text: "No centro de distribuição de %!1, houve uma paralisação causada por falhas no sistema %!2. Operários indicam que o problema teve origem no %!3, afetando o fluxo de %!4. O gerente %!5 acionou a equipe de manutenção que utiliza %!6 para diagnosticar o problema. Enquanto isso, a entrega de %!7 foi redirecionada para centros alternativos. A previsão de resolução é dentro de %!8 horas. Clientes foram notificados sobre o atraso e o suporte %!9 está ativo para auxiliar. Sinais indicam que a falha pode ter sido causada por %!10. Protocolos da empresa exigem análise de %!11 antes da reintegração completa dos setores. Técnicos liderados por %!12 estão empenhados em retomar o ritmo normal.",
    count: 12,
    prompts: [
      ["ALIMENTOS", "ELETRONICOS", "VESTUARIO"],
      ["ELETRICO", "LOGISTICO", "COMPUTACIONAL"],
      ["SERVIDOR CENTRAL", "SISTEMA DE TRANSPORTE", "LINHA DE MONTAGEM"],
      ["PRODUTOS", "MATERIAIS", "MERCADORIAS"],
      ["SILVA", "PEREIRA", "GOMES"],
      ["ESCANERS", "ANALISADORES", "SENSORES"],
      ["ENCOMENDAS EXPRESSAS", "CAIXAS DE REPOSICAO", "MATERIAIS PRIORITARIOS"],
      ["8", "12", "24"],
      ["AO CLIENTE", "AO SUPORTE", "AO CALL CENTER"],
      ["SOBRECARGA", "VIRUS DE COMPUTADOR", "ERRO HUMANO"],
      ["LOGISTICA", "SAUDE E SEGURANCA", "TECNOLOGIA DA INFORMACAO"],
      ["ENGENHEIRO RICARDO", "TECNICO MARIA", "SUPERVISOR FELIPE"],
    ],
  },
  {
    text: "Durante o torneio internacional de futsal em %!1, a equipe %!2 surpreendeu os espectadores com uma jogada %!3. O jogador %!4 marcou o gol decisivo aos %!5 minutos do segundo tempo. A torcida compareceu em massa na arena %!6, trazendo um ambiente %!7. O treinador %!8 destacou a importância da técnica %!9 e da preparação física. O adversário %!10 tentou pressionar, mas foi derrotado com um placar de %!11. O próximo confronto será contra %!12.",
    count: 12,
    prompts: [
      ["LISBOA", "MADRID", "MILAO"],
      ["CAMPEOES", "INVASORES", "GUERRILHEIROS"],
      ["INOVADORA", "IMPLACAVEL", "ESPETACULAR"],
      ["FERNANDO", "RAFAEL", "JOSE"],
      ["42", "38", "47"],
      ["OLIMPICA", "REAL", "ATHENAS"],
      ["ELETRIZANTE", "ANIMADO", "UNIDO"],
      ["SANTOS", "RODRIGUES", "FERREIRA"],
      ["DEFESA", "ATAQUE", "COESAO"],
      ["VIKINGS", "VALENTES", "TITAS"],
      ["4-2", "3-1", "5-3"],
      ["RIVERA", "COSTA", "LOPES"],
    ],
  },
  {
    text: "No bairro %!1, as casas foram afetadas por uma chuva de granizo que causou danos em %!2. Vários moradores relataram quedas de %!3 e interrupções no fornecimento de %!4. Equipes de reparação estão atuando principalmente nas ruas %!5 e %!6. O prefeito %!7 declarou estado de emergência e solicitou ajuda de %!8, incluindo %!9 para aliviar o problema. A polícia reforçou patrulhamento para evitar %!10. Comunidades estão orientadas a usar %!11 e a seguir recomendações de segurança. A previsão indica melhora do tempo em %!12 horas.",
    count: 12,
    prompts: [
      ["SANTA MARIA", "JARDIM DAS FLORES", "VILA NOVA"],
      ["TELHADOS", "VEICULOS", "VIDROS"],
      ["ARVORES", "LUMINARIAS", "ANTENAS DE TV"],
      ["AGUA", "ELETRICIDADE", "GAS"],
      ["PRIMAVERA", "VERDE", "PAULISTA"],
      ["SAO JOAO", "CENTRO", "GUARUJA"],
      ["COSTA", "MENDES", "SILVA"],
      ["DEFESA CIVIL", "CORPO DE BOMBEIROS", "EXERCITO"],
      ["ABRIGOS MOVEIS", "EQUIPAMENTOS DE EMERGENCIA", "ALIMENTACAO"],
      ["SAQUES", "VANDALISMOS", "FURTOS"],
      ["GERADORES", "ILUMINACAO DE EMERGENCIA", "CAIXAS DE PRIMEIROS SOCORROS"],
      ["24", "36", "48"],
    ],
  },
  {
    text: "No museu %!1, uma exposição temporária apresenta artefatos %!2 recuperados de escavações em %!3. Entre os objetos, destaca-se %!4, datado do século %!5. Os visitantes podem interagir por meio de %!6 e aprender sobre %!7. A curadoria enfatiza a importância cultural dos achados e sua relação com %!8. Foi lançada uma série de palestras sobre %!9, abertas ao público. A popularidade do evento tem sido %!10 e apoio do governo foi confirmado por %!11. A exposição permanece aberta até %!12.",
    count: 12,
    prompts: [
      ["NACIONAL", "DE HISTORIA", "DE ARTE"],
      ["PRE-HISTORICOS", "MEDIEVAIS", "INVASOES"],
      ["EGITO", "MESOPOTAMIA", "GRECIA"],
      ["UM COFRE DE OURO", "UMA ARMA CERIMONIAL", "UMA ESTATUA DE MARFIM"],
      ["IX", "XV", "XVIII"],
      ["REALIDADE VIRTUAL", "VIDEO INTERATIVO", "APLICATIVOS"],
      ["CIVILIZACOES ANTIGAS", "ARTES SAGRADAS", "TECNOLOGIA ANCESTRAL"],
      ["MITOLOGIA", "ARMAS", "RELIGIOES"],
      ["ARQUEOLOGIA", "ANTROPOLOGIA", "HISTORIA"],
      ["ALTAMENTE", "MODERADA", "EM ASCENSAO"],
      ["MINISTERIO DA CULTURA", "PREFEITURA", "INSTITUTO DE PATRIMONIO"],
      ["31 DE DEZEMBRO", "30 DE NOVEMBRO", "31 DE OUTUBRO"],
    ],
  },
  {
    text: "No centro tecnológico %!1, uma startup desenvolve soluções baseadas em %!2 para melhorar %!3 em grandes cidades. Recentemente, adotaram %!4 para testar a eficiência energética. Um dos desafios enfrentados inclui %!5, que impacta diretamente no %!6. A equipe de desenvolvimento, liderada por %!7, anunciou avanços significativos em %!8. O mercado tem mostrado interesse principalmente em %!9 e %!10. Parcerias estratégicas com %!11 impulsionam o projeto. A previsão para lançamento comercial é em %!12.",
    count: 12,
    prompts: [
      ["INOVACAO", "TECNOLOGIA AVANCADA", "PANDORA LABS"],
      ["INTELIGENCIA ARTIFICIAL", "INTERNET DAS COISAS", "REDES 5G"],
      ["GESTAO DE TRAFEGO", "CONTROLE DE ENERGIA", "MONITORAMENTO URBANO"],
      ["SENSORES INTELIGENTES", "ANALITICA DE DADOS", "DISPOSITIVOS AUTONOMOS"],
      ["CONGESTIONAMENTO", "INTERFERENCIAS", "FALHAS DE SISTEMA"],
      ["PROCESSAMENTO DE INFORMACAO", "DISTRIBUICAO DE RECURSOS", "AUTOMACAO"],
      ["DRA. FERREIRA", "ENG. OLIVEIRA", "DR. SANTOS"],
      [
        "APRIMORAMENTO DE SOFTWARE",
        "REDUCAO DE ERROS",
        "INTEGRACAO DE SISTEMAS",
      ],
      ["SEGURANCA", "EFICIENCIA", "ECONOMIA DE CUSTOS"],
      ["SOLUCOES CORPORATIVAS", "APLICACOES DOMESTICAS", "PLATAFORMAS MOVEIS"],
      [
        "EMPRESAS DE TELECOMUNICACOES",
        "GOVERNO MUNICIPAL",
        "INSTITUICOES ACADEMICAS",
      ],
      ["18 MESES", "24 MESES", "36 MESES"],
    ],
  },
  {
    text: "No hospital %!1, a equipe médica implantou um novo protocolo para tratamento de %!2. Os avanços em %!3 têm melhorado significativamente a recuperação dos pacientes. O equipamento %!4 foi adquirido recentemente e contribui para diagnósticos mais precisos. As enfermarias %!5 receberam melhorias estruturais para maior conforto. Pacientes com %!6 são acompanhados por times especializados. Uma campanha educativa foca em prevenção contra %!7. O médico %!8 integra uma força-tarefa para modernizar %!9. As expectativas são otimistas, com reduções em %!10 e aumento na %!11. A implementação do protocolo foi financiada por %!12.",
    count: 12,
    prompts: [
      ["SANTA MARIA", "SAO LUIZ", "NOSSA SENHORA"],
      ["DOENCA CARDIACA", "DIABETES", "CANCER"],
      ["TECNOLOGIAS ROBOTICAS", "TERAPIAS GENETICAS", "MEDICINA PERSONALIZADA"],
      ["DE RESSONANCIA MAGNETICA", "DE RAIOS-X", "DE ULTRASSONOGRAFIA"],
      ["PEDIATRICAS", "GERIATRICAS", "INTENSIVAS"],
      ["CONDICOES CRONICAS", "INFECCOES", "ALERGIAS"],
      ["DIABETES", "HIPERTENSAO", "OBESIDADE"],
      ["DOUTOR ALMEIDA", "DOUTORA SOUSA", "DOUTOR COSTA"],
      ["REDES HOSPITALARES", "ATENDIMENTO DOMICILIAR", "SUPORTE CLINICO"],
      ["TEMPO DE INTERNACAO", "TAXAS DE REINTERNACAO", "COMPLICACOES"],
      [
        "QUALIDADE DE VIDA",
        "SATISFACAO DOS PACIENTES",
        "EFICACIA DO TRATAMENTO",
      ],
      ["FUNDACAO SAUDE", "MINISTERIO DA SAUDE", "DOACOES PRIVADAS"],
    ],
  },
  {
    text: "Durante a expedição submarina nas águas de %!1, a equipe descobriu uma escola de %!2 nadando próxima a uma formação rochosa. As condições da água apresentavam %!3, dificultando a visibilidade. Equipamentos como %!4 foram essenciais para o registro das imagens. O comandante %!5 ressaltou a importância de preservar a região contra %!6. Pesquisas indicam que essas espécies são vitais para %!7. Equipamentos de segurança alertaram sobre %!8 inesperados. O retorno à base está previsto para %!9. Novas áreas a explorar incluem %!10 e %!11. O relatório final será entregue à %!12.",
    count: 12,
    prompts: [
      ["MAR MEDITERRANEO", "OCEANO PACIFICO", "ATLANTICO SUL"],
      ["TUBAROES", "ARRAIAS", "CAVALOS-MARINHOS"],
      ["CORRENTES FORTES", "TEMPERATURAS BAIXAS", "TURBIDEZ"],
      ["SONARES", "CAMERAS SUBMARINHAS", "LAMPS DE LED"],
      ["CAPITAO RIBEIRO", "LIEUTENANT SILVA", "ENGENHEIRO MELO"],
      ["PESCA ILEGAL", "POLUICAO", "TURISMO DESCONTROLADO"],
      ["EQUILIBRIO ECOLOGICO", "MANUTENCAO DO RECIFE", "PROTECAO DA FAUNA"],
      [
        "PRESENCA DE CRUSTACEOS",
        "MOVIMENTOS DE CARDUMES",
        "AVISOS DE TECTONICOS",
      ],
      ["AMANHA", "2 DIAS", "1 SEMANA"],
      ["CAVERNA SUBMARINA", "VULCAO SUBMARINO", "NAVIO AFUNDADO"],
      ["ILHAS PROXIMAS", "RECIFES DE CORAL", "ZONAS DE MUDANCA"],
      [
        "INSTITUTO OCEANOGRAFICO",
        "ACADEMIA DE CIENCIAS MARINHAS",
        "FUNDACAO AMBIENTAL",
      ],
    ],
  },
  {
    text: "Durante o teste da nova arma %!1 no campo de provas de %!2, foi detectada uma instabilidade no sistema %!3. O engenheiro %!4 recomendou a suspensão do teste após observar %!5, que poderia causar %!6. A equipe de segurança ativou o protocolo %!7 para evacuação rápida. O efeito da instabilidade foi percebido em %!8 metros ao redor do ponto de teste. Dados preliminares indicam que o componente %!9 falhou devido a %!10. O monitoramento contínuo será feito pela %!11. O sucesso do teste determinará a liberação para uso em %!12.",
    count: 12,
    prompts: [
      ["LASER DE PULSO", "CANHAO DE PARTICULAS", "MISSIL IONICO"],
      ["ALFA", "BETA", "GAMA"],
      ["DE REFRIGERACAO", "DE DISPARO", "DE CONTROLE"],
      ["ENG SANTOS", "ENG LIMA", "ENG MENDES"],
      ["SOBREAQUECIMENTO", "VIBRACOES EXCESSIVAS", "DESCOMPENSAO MAGNETICA"],
      ["DANOS CATASTROFICOS", "FALHAS NO HARDWARE", "RISCOS DE SEGURANCA"],
      ["VERDE", "AMARELO", "VERMELHO"],
      ["500", "1000", "1500"],
      ["MODULADOR", "CAPACITOR", "TRANSDUTOR"],
      ["SOBRECARGA ELETRICA", "FALHA MECANICA", "ERRO DE PROGRAMACAO"],
      ["LABORATORIO CENTRAL", "CENTRO DE PESQUISA", "UNIDADE DE TESTES"],
      ["USO MILITAR", "CIVIL", "COMERCIAL"],
    ],
  },

  {
    text: "Durante a missão no planeta %!1, a equipe detectou uma anomalia no sistema %!2. Sensores indicaram uma alteração incomum na %!3. O comandante %!4 ordenou a evacuação da área %!5 para evitar riscos à tripulação. Equipamentos de proteção, como %!6, foram utilizados para conter possíveis efeitos da %!7. O relatório inicial sugere que o fenômeno está relacionado a %!8. Cientistas do %!9 investigam a possibilidade de vida microbiana em %!10. A comunicação com a base %!11 foi restabelecida após %!12 horas.",
    count: 12,
    prompts: [
      ["XENON", "ALTARIS", "NOVA TERRA"],
      ["DE SUPORTE VITAL", "DE NAVEGACAO", "DE COMUNICACAO"],
      ["ATMOSFERA", "CAMPO MAGNETICO", "GRAVIDADE"],
      ["SARGENTO MENDES", "CAPITAO LIMA", "TENENTE SILVA"],
      ["WESTEROS", "SECTOR 7", "AREA AZUL"],
      [
        "TRAJES ANTI-RADIACAO",
        "MASCARAS DE OXIGENIO",
        "BARREIRAS DE CONFINAMENTO",
      ],
      ["ANOMALIA QUANTICA", "RADIOATIVIDADE", "TEMPORALIDADE ALTERADA"],
      ["ORGANISMO DESCONHECIDO", "SAIS MINERAIS", "DECOMPOSICAO CELULAR"],
      [
        "INSTITUTO ESPACIAL",
        "CENTRO DE PESQUISA GALACTICA",
        "ACADEMIA COSMICA",
      ],
      ["SAMPLE 42", "AMOSTRA ALPHA", "ITEM DELTA"],
      ["ORBITAL", "BASE TERRESTRE", "ESTACAO DE IMPACTO"],
      ["3", "5", "7"],
    ],
  },
  {
    text: "No reino de %!1, o exército do %!2 se prepara para invadir a fortaleza em %!3. O rei %!4 enviou espiões para descobrir o número de %!5 inimigos e sua localização em %!6. As forças de arcabuz mantém vigilância no portão %!7, enquanto a cavalaria %!8 aguarda a ordem para avançar. O chefe da guarda, %!9, relatou movimentações suspeitas perto das florestas de %!10. Um mensageiro secreto foi visto carregando documentos referentes à %!11 que pode determinar o resultado da guerra. As próximas batalhas ocorrerão no vale de %!12.",
    count: 12,
    prompts: [
      ["ARKHADIA", "NORDHAVEN", "VELDARIS"],
      ["IMPERIO SOMBRIO", "TRIBOS DO FOGO", "CLA DA LUZ"],
      ["CASTELO DRAVEN", "FORTALEZA VERMELHA", "TORRE DE MIDGARD"],
      ["EDUARDO IV", "ALARICO II", "THEODORO III"],
      ["SOLDADOS", "CAVALEIROS", "ARQUEIROS"],
      ["VALE GELADO", "PLANALTO DE ELMER", "COLINAS DE ELDOR"],
      ["ORIENTAL", "PRINCIPAL", "OESTE"],
      ["REAL", "LIGEIRA", "DA FLORESTA"],
      ["GENERAL KALON", "COMANDANTE RHEYN", "ALCAIDE ZAR"],
      ["DRUMMOND", "FENRIR", "ASHENWOOD"],
      ["UM ALIANCA", "A TRATADO DE PAZ", "A CONSPIRACAO"],
      ["MARETE", "GLASUVAN", "WINDHOLLOW"],
    ],
  },
  {
    text: "Na metrópole %!1, sistemas automatizados controlam %!2, incluindo os veículos e o fornecimento de %!3. Recentemente, um ataque hacker conseguiu infiltrar um vírus denominado %!4, comprometendo %!5. A empresa %!6 contratou o especialista %!7 para neutralizar a ameaça. Foram identificadas falhas no firewall %!8 e nos protocolos de segurança %!9. Em casos de emergência, os canais %!10 e %!11 são ativados automaticamente. A previsão para restaurar o sistema é em %!12 horas.",
    count: 12,
    prompts: [
      ["NEO-CIDADE", "CYBERLAND", "METROPOLE X"],
      [
        "ILUMINACAO PUBLICA",
        "SISTEMA DE TRANSPORTE",
        "ABASTECIMENTO DE ENERGIA",
      ],
      ["AGUA", "ELETRICIDADE", "INTERNET"],
      ["BLACKOUT", "PHANTOM", "SHADOWNET"],
      ["REDES DE COMANDO", "CENTRAIS DE CONTROLE", "SENSORES"],
      ["TECHWAR", "NETGUARD", "CYBERSHIELD"],
      ["DR. REYES", "ENG. KIM", "DRA. MORENO"],
      ["PRIMARIO", "SECUNDARIO", "TERCIARIO"],
      ["DE DADOS", "DE AUTENTICACAO", "DE MONITORAMENTO"],
      ["SMS", "EMAIL", "APLICATIVOS DE EMERGENCIA"],
      ["SISTEMAS DE ALERTA", "RADIOS DE EMERGENCIA", "SINAIS SONOROS"],
      ["6", "12", "24"],
    ],
  },
  {
    text: "Em %!1, a equipe de arqueologia descobriu ruínas enterradas que podem remontar à civilização %!2. Entre os artefatos estão %!3, que apresentam inscrições em %!4. O sítio está localizado próximo ao %!5, considerado sagrado para os povos ancestrais. A escavação enfrenta desafios com %!6 e a necessidade de proteger %!7 dos fundos públicos. A equipe liderada por %!8 utiliza %!9 para mapear os locais de interesse. Recentemente, um fragmento %!10 foi identificado como peça-chave na compreensão do sistema %!11. A expectativa é que o estudo contribua para o conhecimento de %!12.",
    count: 12,
    prompts: [
      ["TEOTIHUACAN", "MACHU PICCHU", "POMPEIA"],
      ["MAIA", "INALA", "ETRUSCA"],
      ["CERAMICAS", "ESTATUAS", "PINTURAS MURAIS"],
      ["HIEROGLIFICOS", "LINGUA PERDIDA", "SIMBOLOS ANTIGOS"],
      ["RIO SACREDO", "MONTANHA AZUL", "VALE DAS SOMBRAS"],
      [
        "CONDICOES CLIMATICAS ADVERSAS",
        "PREDADORES LOCAIS",
        "RISCO DE DESABAMENTOS",
      ],
      ["OS EQUIPAMENTOS", "OS FUNCIONARIOS", "OS ARQUEOLOGOS"],
      ["PROF. GARCIA", "DRA. LOPEZ", "DR. MARTINS"],
      ["TECNOLOGIA LIDAR", "DRONES", "GEORADAR"],
      ["DE CERAMICA", "DE PEDRA", "DE METAL"],
      ["DE RELIGIAO", "DE AGRICULTURA", "DE MITOLOGIA"],
      ["HISTORIA ANTIGA", "ANTROPOLOGIA", "ARQUEOLOGIA"],
    ],
  },
  {
    text: "Na cidade %!1, a taxa de criminalidade associada a %!2 aumentou significativamente. As autoridades implementaram o programa %!3 para combater crimes relacionados a %!4. Oficiais têm intensificado patrulhas em bairros %!5 e %!6. A tecnologia %!7 tem auxiliado no monitoramento e captura de suspeitos. O delegado %!8 afirma que a colaboração comunitária é fundamental. Casos recentes envolvem %!9 e %!10, que têm assustado os moradores. Campanhas educativas estão previstas para reduzir %!11. Estima-se que o índice diminua significativamente após %!12 meses de ações contínuas.",
    count: 12,
    prompts: [
      ["SANTO ANGELO", "GRANDE VILA", "PORTO NOVO"],
      ["FURTOS", "TRAFICO", "VANDALISMO"],
      ["SEGURANCA ACTIVA", "CIDADE UNIDA", "PATRULHA LEGAL"],
      ["DROGAS", "ARMAS", "ROUBOS"],
      ["CENTRAL", "LESTE", "SUL"],
      ["NORTE", "OESTE", "CENTRO"],
      ["CAMERAS DE VIGILANCIA", "DRONES", "SISTEMAS DE ALARME"],
      ["FERREIRA", "SILVA", "ALMEIDA"],
      ["ROUBOS A COMERCIANTES", "ATAQUES A PEDESTRES", "INVASOES DOMICILIARES"],
      ["USO DE SUBSTANCIAS", "VIOLENCIA DOMESTICA", "DISPUTAS TRAFICANTES"],
      ["A DELINQUENCIA", "O DESINTERESSE SOCIAL", "A IMPUNIDADE"],
      ["6", "12", "18"],
    ],
  },
];

console.log(stories[31])

const PATTERN = {
  0: 1,
  1: 2,
  2: 3,
  3: 4,
  4: 5,
  5: 6,
  6: 7,
  7: 8,
  8: 9,
  9: 10,
  A: 11,
  B: 12,
  C: 13,
  D: 14,
  E: 15,
  F: 16,
  G: 17,
  H: 18,
  I: 19,
  J: 20,
  K: 21,
  L: 22,
  M: 23,
  N: 24,
  O: 25,
  P: 26,
  Q: 27,
  R: 28,
  S: 29,
  T: 30,
  U: 31,
  V: 32,
  W: 33,
  X: 34,
  Y: 35,
  Z: 36,
  " ": 37,
  "%": 38,
  ".": 39,
  "-": 40,
};

function verifyChars(stories) {
  let s = 0;
  for (const story of stories) {
    let p = 0;

    for (const prompts of story.prompts) {
      for (const prompt of prompts) {
        const chars = prompt.split("");

        for (const char of chars) {
          if (!(char in PATTERN)) {
            console.log(char, s, p);
          }
        }
      }

      p++;
    }

    s++;
  }
}

verifyChars(stories);
