import leoProfanity from "leo-profanity";

leoProfanity.loadDictionary("en");

const bannedWords = [
  // Português do Brasil
  "merda",
  "porra",
  "caralho",
  "puta",
  "fdp",
  "filho da puta",
  "filha da puta",
  "desgraçado",
  "babaca",
  "bosta",
  "vagabunda",
  "arrombado",
  "corno",
  "otário",
  "escroto",
  "piranha",
  "viado",
  "boiola",
  "retardado",
  "puta que pariu",
  "cu",
  "tomar no cu",
  "vai tomar no cu",
  "pau no cu",
  "cacete",
  "buceta",
  "rola",
  "piroca",
  "xoxota",
  "mijado",
  "nojento",
  "desgraça",
  "maldito",

  // Português de Portugal
  "cona",
  "foda-se",
  "vai-te foder",
  "cabrão",
  "paneleiro",
  "estúpido",
  "parvo",
  "caralhadas",
  "caralho",
  "merdas",
  "filho da mãe",
  "puta da tua mãe",
  "puta que te pariu",
  "chupa",
  "vai levar no cu",
  "otária",
  "ganda puta",
  "apanha no cu",
  "palhaço",
  "pila",
  "ranhoso",
  "chato do caralho",
  "fuck",
  "shit",
  "asshole",
  "bitch",
  "bastard",
  "dick",
  "pussy",
  "cock",
  "fucker",
  "motherfucker",
  "son of a bitch",
  "slut",
  "whore",
  "damn",
  "douche",
  "bollocks",
  "arse",
  "wanker",
  "prick",
  "cunt",
];

leoProfanity.add(bannedWords);

export function verifyBadWords(name: string): boolean {
  return leoProfanity.check(name);
}
